sonar.projectKey=plantillas_mid
sonar.projectName=plantillas_mid
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/vendor/**, **/swagger/**, **/build/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.sourceEncoding=UTF-8
