appname = plantillas_mid
httpport = 8087
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

PlantillasCrudService = ${PLANTILLAS_CRUD_SERVICE}

RenderizadoPlantillas = ${PLANTILLAS_MID_RENDERIZADO_PLANTILLAS}
