appname = plantillas_mid
httpport = 8080
runmode = ${PLANTILLAS_MID_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true

PlantillasCrudService = ${PLANTILLAS_CRUD_SERVICE}
RenderizadoPlantillas = ${PLANTILLAS_MID_RENDERIZADO_PLANTILLAS}
